# Generated by Django 3.0.5 on 2020-05-21 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_professor'),
        ('courses', '0002_auto_20200519_0930'),
    ]

    operations = [
    ]
