# Generated by Django 3.0.5 on 2020-05-20 22:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
