# Generated by Django 3.0.5 on 2020-05-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_auto_20200521_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handout',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
